[tox]
envlist =
    py3{8,9,10,11,12,13,14}-httpx
    py3{10,11,12,13,14}-httpx2

[testenv]
deps =
    httpx: -r requirements/tests-httpx.txt
    httpx2: -r requirements/tests.txt
setenv =
    httpx: NOTION_HTTP_BACKEND=httpx
    httpx2: NOTION_HTTP_BACKEND=httpx2
commands = pytest
