from datetime import datetime

import pytest


def compare_cleaned_url(url1: str, url2: str) -> bool:
    return url1.replace("-", "").strip() == url2.replace("-", "").strip()


# USERS


def test_users_list(client):
    response = client.users.list()
    assert response["type"] == "user"
    assert response["results"][0]["name"] == "Notion Testing Account"


def test_users_me(client):
    response = client.users.me()
    assert response["type"] == "bot"
    assert response["id"]


def test_users_retrieve(client):
    me = client.users.me()
    response = client.users.retrieve(me["id"])
    assert response == me


# PAGES
# the first test generates a temporary page and uses its ID as input for the other tests


@pytest.fixture(scope="session")
def test_pages_create(client, testing_page):
    page_name = f"Test Page - {datetime.now()}"
    response = client.pages.create(
        parent={"page_id": testing_page},
        properties={
            "title": [{"text": {"content": page_name}}],
        },
        # using children = [] for avoiding issue with the Notion API
        # when creating a subpage without blocks
        children=[],
    )

    yield response["id"]

    # at the end of the session, delete the page
    client.blocks.delete(block_id=response["id"])


def test_pages_retrieve(client, test_pages_create, testing_page):
    response = client.pages.retrieve(page_id=test_pages_create)
    assert response["object"] == "page"
    assert compare_cleaned_url(response["parent"]["page_id"], testing_page)


def test_pages_update(client, test_pages_create):
    icon = {"type": "emoji", "emoji": "🛴"}

    response = client.pages.update(page_id=test_pages_create, icon=icon)
    assert response["icon"] == icon


def test_pages_properties_retrieve(client, test_pages_create):
    response = client.pages.properties.retrieve(
        page_id=test_pages_create, property_id="title"
    )
    assert response["results"][0]["type"] == "title"


# SEARCH
# TODO: see test

# DATABASES
# the first test generates a temporary database inside
# the main page generated by test_pages_create and uses
# its ID as input for the other tests in the DATABASES section


@pytest.fixture(scope="session")
def test_databases_create(client, test_pages_create):
    db_name = f"Test Database - {datetime.now()}"
    properties = {
        "Name": {"title": {}},  # required property
    }
    title = [{"type": "text", "text": {"content": db_name}}]
    parent = {"type": "page_id", "page_id": test_pages_create}
    response = client.databases.create(
        **{"parent": parent, "title": title, "properties": properties}
    )

    #  the test returns the ID of the newly created database for the other tests
    return response["id"]


def test_databases_retrieve(client, test_databases_create, test_pages_create):

    response = client.databases.retrieve(test_databases_create)
    assert compare_cleaned_url(response["id"], test_databases_create)
    assert response["object"] == "database"
    assert compare_cleaned_url(response["parent"]["page_id"], test_pages_create)


def test_databases_query(client, test_databases_create):
    query = {
        "database_id": test_databases_create,
        "filter": {"timestamp": "created_time", "created_time": {"past_week": {}}},
    }

    response = client.databases.query(**query)
    assert response["object"] == "list"
    # results should be empty, the testing DB has no rows
    assert not response["results"]


def test_databases_update(client, test_databases_create):
    icon = {"type": "emoji", "emoji": "🔥"}

    response = client.databases.update(database_id=test_databases_create, icon=icon)
    assert response["icon"] == icon
