name: Links Check

on:
  repository_dispatch:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "00 7 * * *"

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@7cd0af4c74a61395d455af97419279d86aafaede  # v2.0.2
        with:
          fail: true
          args: >-
            --exclude '.*(\{|%7B).*(\}|%7D).*'
            --exclude 'https://www/$'
            --exclude '\.slack\.com'
            --exclude-path tests
            --exclude-path docs/SUMMARY.md
            '**/*.md' '**/*.py'
